/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Nume]
      ,[Cod]
      ,[Numar]
      ,[Marca]
      ,[Serie]
      ,[Kilometraj]
      ,[An]
      ,[Poluare]
      ,[Data]
      ,[Statie]
      ,[Minim]
      ,[Maxim]
      ,[Total]
  FROM [Parc_Auto].[dbo].[Masini]